import random

template = input("Enter a, b, c or you can choose and write random")

if template == "random":
    a = ['a','b','c']
    template = random.choice(a)  
    
if template == 'a':
    print("story a")
    number = input ("Input a number:")
    measureoftime = input(" Input Measure of time:")
    modeoftransportation = input ("Input Mode Of Transportation:")
    adjective = input ("Input Adjective:")
    adjective2 = input ("Input Adjective2:")
    noun = input ("Input Noun:")
    color = input ("Input Color:")
    partofthebody = input ("Imput Part of the body:")
    verb = input ("Input Verb:")
    number2 = input ("Input Number2:")
    noun2 = input ("Input Noun2:")
    noun3 = input ("Input Noun3:")
    partofthebody2 = input("Input Part of the body2:")
    verb2 = input ("Input Verb2:")
    noun4 = input ("Imput Noun3:")
    adjective3 = input ("Imput Adjective3:")
    sillyword = input ("Imput Silly word:")
    noun5 = input ("Input Noun4:")
    print(f"It was about {number} {measureoftime} ago when I arrived at the hospital in a {modeoftransportation}. The hospital is a/an {adjective} place, there are a lot of {adjective2} {noun} here. There are nurses here who have {color} {partofthebody }. If someone wants to come into my room I told them that they have to {verb} first. I have decorated my room with {number2} {noun2}. Today I talked to a doctor and they were wearing a {noun3} on their {partofthebody2}. I heard that all doctors {verb2} {noun4} every day for breakfast. The most {adjective3} thing about being in the hospital is the {sillyword } {noun5}!")
elif template == 'b':
    print("story b")
    propernoun = input ("Input Proper Noun (Person’s Name):")
    noun = input ("Input noun:")
    adjective = input ("Input Adjective (Feeling):")
    verb=input("Input verb:") 
    adjective2 = input ("Adjective (Feeling2):")
    animal= input("Input animal:")
    verb2 = input ("Input verb2:")
    color = input ("Input color:")
    verb3 =  input ("Input verb (ending in ing):")
    adverb = input("Input adverb (ending in ly):")
    number= input ("Input number:")
    measureoftime = ("Input measure of time:)")
    color2 = input("Input color:")
    animal2 = input("Input animal:") 
    number2 = input ("Input number2:")
    sillyword = input ("Input silly word:")
    noun2 = input ("Input noun2:")
    print (f"This weekend I am going camping with {propernoun}. I packed my lantern, sleeping bag, and {noun}. I am so {adjective}to {verb} in a tent. I am {adjective2} we might see a(n) {animal}, I hear they’re kind of dangerous. While we’re camping, we are going to hike, fish, and {verb}. I have heard that the {color} lake is great for {verb2}. Then we will {adverb} hike through the forest for {number} {measureoftime}. If I see a {color} {animal} while hiking, I am going to bring it home as a pet! At night we will tell {number} {sillyword} stories and roast {noun2} around the campfire!!")
elif template == 'c':
    print("story c")
    propernoun = input ("Input proper noun (person’s name):")
    adjective = input (" Input adjective:")
    color = input ("Input color:")
    animal = input ("Input animal:")
    place = input ("Input place:")
    adjective2 = input ("Input adjective2:")
    plural = input("Input magical creature (plural):")
    adjective3 = input ("Input adjective3:")
    plural2 = input ("Input magical creature (plural)2):")
    roominahouse = input ("Input room in a house:")
    noun= input ("Input noun:")
    noun2 = input ("input noun:")
    plural3 = input ("Input noun(plural)3):")
    adjective4 = input ("Input adjective4:")
    noun4= input ("Input noun (plural)4):")
    number = input ("Input number:")
    measureoftime = input ("Input measure of time:")
    verb = input ("Input verb (ending in ing:")
    adjective5 = input ("Input adjective5:")
    noun5 = input ("Input noun5:")
    print(f"Dear {propernoun}, I am writing to you from a {adjective} castle in an enchanted forest. I found myself here one day after going for a ride on a {color} {animal} in {place}. There are {adjective2} {plural} and {adjective3}  {plural2} here! In the {roominahouse} there is a pool full of {noun}. I fall asleep each night on a {noun2} of {plural3} and dream of {adjective4} {noun4}. It feels as though I have lived here for {number} {measureoftime}. I hope one day you can visit, although the only way to get here now is {verb} on a {adjective5} {noun5}!!")
else:
    print ("your enter is fauls")   
